### ISSUE TITLE
add function for operating on the result of unwrapping a newtype: through

### ISSUE THREAD

**Issue by cdepillabout** [purescript/purescript-newtype#13]
It'd be nice to have a function that looks like this:

```purescript
through
  :: forall t a b
   . Newtype t a
  => (a -> t) -> (a -> b) -> t -> b                     
through wrapper f t = f (un wrapper t)
```

This is similar to, but slightly different from `over` and `under`:

```purescript
over
  :: forall t a s b
   . Newtype t a
  => Newtype s b
  => (a -> t) -> (a -> b) -> t -> s
over _ f = wrap <<< f <<< unwrap

under
  :: forall t a s b
   . Newtype t a
  => Newtype s b
  => (a -> t) -> (t -> s) -> a -> b
under _ f = unwrap <<< f <<< wrap
```

Would a PR for `through` accepted?

**Comment by paf31** [comment]
It's also `f <<< unwrap`, right? Do you think it's worth having another name to remember here, if it's that short?

**Comment by garyb** [comment]
> Do you think it's worth having another name to remember here, if it's that short?

That was kinda my thinking too - I have wanted this function a few times, but then thought "eh, it's just `f <<< unwrap`" :smile:

Maybe if there's anyone else out there with strong feelings on the matter they could chime in?

**Comment by gomain** [comment]
It indeed is `f <<< unwrap` but this lacks context when used far from the `Newtype` instance.

When someone sees `_.name <<< unwrap` they go "ok, some newtype is wrapping a record that has feild 'name'".

Contrast to `through MyType _.name` they go "ah, 'MyType' is a newtype wrapping a record that has field 'name'"

**Comment by garyb** [comment]
I'd probably actually use `f <<< un MyType`, since I prefer to use the explicit `un` over `unwrap`.

You could write the above example as `un MyType # _.name` if you want to order the expression that way.

**Comment by JordanMartinez** [comment]
Should we close this issue?

**Comment by hdgarrood** [comment]
I’d vote to close too, I think this is too similar to `f <<< un MyType` to deserve a separate named function in this library.
