### ISSUE TITLE
add `into = over wrap`

### ISSUE THREAD

**Issue by safareli** [purescript/purescript-newtype#14]
Might be useful when you want to operate on internal value

```purescript
into
  :: forall t a s b
   . Newtype t a
  => (a -> a)
  -> t
  -> t
into = over wrap
```

**Comment by paf31** [comment]
I think the point of the type of `over` is that it's useful to have the first argument for type inference when you know the oldtype but not the newtype.

I don't think we should add synonyms for such short things as `over wrap`, adding more names to learn, honestly.

**Comment by safareli** [comment]
Ah ok.
And actually using `over wrap` type was not inferred correctly and i needed to use the actual type constructor instead of `wrap`
