### ISSUE TITLE
Split Newtype into two classes that Newtype combines together

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript-newtype#18]
There are times where I want to use a newtype like a compile-time refined type:
```purescript
module WholeInt (WholeInt, mkWholeInt) where

newtype WholeInt = WholeInt Int

mkWholeInt :: Int -> WholeInt
mkWholeInt x | x < 0 = WholeInt 0
             | otherwise = WholeInt x
```
Then, I can guarantee that this type will never store a negative integer. However, by using this approach, `WholeInt` can no longer use some of the same functions from `Newtype`, such as `un`. Rather, I must define an `un`-like function for each newtype like `WholeInt`.

It is possible to split `Newtype` into two classes that are then combined via `Newtype`? Something like below?
```purescript
class Unwrap t a | t -> a where
   unwrap :: t -> a

class Wrap t a | t -> a where
   wrap :: a -> t

class (Unwrap t a, Wrap t a) <= Newtype t a | t -> a
```
I noticed that many functions (such as `un`) take a 'wrap'-like function that seems to help type inference or something.

**Comment by JordanMartinez** [comment]
Three more thoughts on this issue...

First, `monoidmusician` pointed out on Slack that type inference is sometimes an issue with `un` and related functions. Thus, one uses a pointless function in `un` to help the compiler out. This could be an actual function but reusing the newtype/data constructor adds the benefit of readability:
```purescript
un WholeInt five
```
Since my situation requires not exporting the constructor, I would be forced to write and use a pointless function:
```purescript
wi :: WholeInt -> Int
wi _ = 0 -- since this function is never called, it doesn't matter what it returns
```
I would need to do this for each type or resort to using `unsafeCoerce :: (WholeInt -> Int)`, which kills the readability:
```purescript
un (unsafeCoerce :: WholeInt -> Int) five
```
At that point, I might as well write a helper function for each newtype using the convention: `un[NewtypeName]`

Second, I don't know whether one would ever need `Wrap` but not `Unwrap`.

Third, if these two functions were split across two classes, would type inference still be an issue?

**Comment by garyb** [comment]
I don't particularly think that splitting up the class would be useful. It's intended to enable abstraction over newtypes, not just provide an overloaded `wrap`/`unwrap` for the sake of having a common names.

And yes, `un` is the commonly-used version of `unwrap`, which needs the constructor to be passed in, defeating the purpose of this proposal too. It's not always required for type checking, but it's good practice to use, as it ensures you're unwrapping the right thing too - if you introduce a new newtype somewhere, or have layers of newtypes, using `unwrap` indiscriminately might not be doing what you think it's doing.

I'd say that more likely, having a 
``` purescript
class Refined t a | t -> a where
  refine :: a -> Maybe t
  unrefine :: t -> a
```
would offer some utility, as then it could also provide the `Newtype`-style abstractions, but the inference problem would remain there, although it is solvable with explicit type annotations on the input.

**Comment by JordanMartinez** [comment]
> I don't particularly think that splitting up the class would be useful. It's intended to enable abstraction over newtypes, not just provide an overloaded wrap/unwrap for the sake of having a common names.

I only used `un` as an example. `over` provides another function that would be useful to use. 

Still, I see your point. `Refined` could be its own library that uses differently-named functions that are isomorphic to `over` and other related functions. Also, it seems that `Refined` is the dual of `Inject`. Anyway, thanks for responding quickly.
