### ISSUE TITLE
The normaliseDegrees in the documentation is incorrect

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-newtype#6]
From the docs for `under`: https://github.com/purescript/purescript-newtype/blob/d18d17203bf5b4be66641fae18802cc13e40ebf8/src/Data/Newtype.purs#L137

```purescript
normaliseDegrees :: Degrees -> NormalDegrees
normaliseDegrees (Degrees deg) = NormalDegrees (deg `mod` 360.0)
```

`mod` is `const (const 0.0)` for Number - I guess we want `%` from Math instead?

**Comment by hdgarrood** [comment]
This makes me worry about the current structure of the Prelude hierarchy, actually. `mod` seems a bit like an unnecessary sharp edge to me.

**Comment by garyb** [comment]
I think it's fine, as long as we've had `mod` it's behaved this way - I was eager to just get this library done so we could start on other dependencies, so made no attempt to see if the examples even compile, never mind checked whether they behaved correctly - if I'd done so it would have been pretty obvious.
